feat: resolver to update item
the important part here is that the where is an object. if it's not
properly set GraphQL will error:
> Error: GraphQL error: Variable "$_v1_where" got invalid value "x";
> Expected type to be an object

The _v1_ is because it's the second element in the object. It'd be v0
if it was first.